model:
  _convert_: all
  img_size:
  - 32
  - 128
  max_label_length: 25
  charset_train: 0123456789abcdefghijklmnopqrstuvwxyz
  charset_test: 0123456789abcdefghijklmnopqrstuvwxyz
  batch_size: 384
  weight_decay: 0.0001
  warmup_pct: 0.05
  name: pimnet_womimic
  _target_: strhub.models.pimnet.womimic_system.PIMNet
  patch_size:
  - 4
  - 8
  embed_dim: 384
  enc_num_heads: 6
  enc_mlp_ratio: 4
  enc_depth: 12
  dec_num_heads: 12
  num_iter: 5
  dropout: 0.1
  lr: 0.0003
data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: /scratch/yang.xiaome/datasets/STR_dataset
  train_dir: synth
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: true
  augment: true
  num_workers: 3
trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  val_check_interval: 1000
  max_epochs: 10
  gradient_clip_val: 20
  gpus: 4
ckpt_path: null
pretrained: null
