- charset=36_lowercase
- dataset=synth
- trainer.gpus=4
- model=pimnet
- model.name=pimnet_womimic
- model._target_=strhub.models.pimnet.womimic_system.PIMNet
- trainer.max_epochs=10
- model.lr=3e-4
- model.warmup_pct=0.05
- model.weight_decay=1e-4
